site:
  title: Eventicle JS
  url: https://book.eventicle.com/
  start_page: eventiclejs::index.adoc
content:
  sources:
    - url: https://github.com/eventicle/eventiclejs.git
      branches: [ master ]
      start_path: docs
      version: true
    - url: https://github.com/eventicle/eventicle-utilities.git
      branches: [ main ]
      start_path: docs
      version: true
    - url: https://github.com/eventicle/datastore-postgres.git
      branches: [ main ]
      start_path: docs
      version: true
ui:
  bundle:
    url: https://github.com/eventicle/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: CNAME
      contents: |
        book.eventicle.com
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
      script_stem: header-scripts
      mermaid_initialize_options: "{ startOnLoad: true }"
output:
  clean: true