site:
  title: Eventicle JS
  url: https://book.eventicle.com/
  start_page: eventiclejs::index.adoc
content:
  sources:
    - url: https://github.com/eventicle/eventiclejs.git
      branches: [doc-update]
      start_path: docs
      version: true
ui:
  bundle:
    url: https://github.com/eventicle/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true