site:
  title: Eventicle JS
  url: https://book.eventicle.com/
  start_page: eventiclejs::index.adoc
content:
  sources:
    - url: https://github.com/eventicle/eventiclejs.git
      branches: [doc-update, v{0..9}*]
      tags: [v{0..9}*]
      start_path: docs
      version: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true